---
title: Bryan King | Web designer and developer | Cincinnati, Ohio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:collection/:title.html"
  uploads:
    title: Uploads
    output: true
logo: brykng
email: bpking15@gmail.com
description: Bryan King is a front-end web developer and designer living in Cincinnati,
  OH. He helps businesses build highly usable, accessible, and intuitive experiences
  for the internet.
baseurl: ''
url: https://brykng.com
twitter_username: brykng
github_username: brykng
dribbble_username: brykng
codepen_username: brykng
twitter:
  username: brykng
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
sass:
  style: compressed
permalink: "/blog/:title.html"
